title: Around IT In 256 Seconds By Tomasz Nurkiewicz
tagline: Around IT In 256 Seconds By Tomasz Nurkiewicz
description: Podcast for developers, testers, SREs… and their managers. I explain complex and convoluted technologies in a clear way, avoiding buzzwords and hype. Never longer than 4 minutes and 16 seconds.
logo: img/cover-800.jpg
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://256.nurkiewicz.com"
twitter_username: tnurkiewicz
github_username:  nurkiewicz
defaults:
  - scope:
      path: ""
    values:
      image: img/cover-800.jpg
      author: Tomasz Nurkiewicz

twitter:
  username: tnurkiewicz
  card: summary

# Build settings
# remote_theme: wowthemesnet/mediumish-theme-jekyll
# remote_theme: wowthemesnet/mundana-theme-jekyll
# remote_theme: samesies/barber-jekyll
remote_theme: brianmaierjr/long-haul

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

repository: nurkiewicz/256
